cursos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.listado_cursos_view, name='listado_cursos'),
    path('agregar_curso/', views.agregar_curso_view, name='agregar_curso'),
    path('modificar_curso/<str:id>', views.modificar_curso_view, name='modificar_curso'),
    path('detalle_curso/<str:id>', views.detalle_curso_view, name='detalle_curso'),
    path('modificar_detalle_docente/<int:id>', views.modificar_detalle_docente_view, name='modificar_detalle_docente'),
    path('eliminar_detalle_docente/<int:id>', views.delete_detalle_docente_view, name='eliminar_detalle_docente'),
    path('modificar_cronograma_actividad/<int:id>', views.modificar_cronograma_actividad_view, name='modificar_cronograma_actividad'),
    path('eliminar_cronograma_actividad/<int:id>', views.delete_cronograma_actividad_view, name='eliminar_cronograma_actividad'),
    path('eliminar_trabajo/<int:id>', views.delete_banco_trabajo_view, name='eliminar_trabajo'),
]

fichas_alumnos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.listado_fichas_alumnos_view, name='listado_fichas_alumnos'),
    path('agregar_ficha', views.form_agregar_ficha_alumno, name='agregar_ficha_alumno'),
    path('ficha_alumno/<str:rut>', views.ficha_alumno_view, name='ficha_alumno'),
    path('modificar_ficha/<str:rut>', views.change_ficha_alumno, name='change_ficha_alumno'),
    path('modificar_avance/<int:id>', views.change_avance_alumno, name='modificar_avance_alumno'),
    path('eliminar_avance/<int:id>', views.delete_avance_alumno, name='eliminar_avance_alumno'),
    path('eliminar_trabajo/<int:id>', views.delete_banco_trabajo, name='eliminar_trabajo_alumno'),
    path('eliminar_documento/<int:id>', views.delete_banco_documento, name='eliminar_documento_alumno'),
    path('retirar_ficha_alumno/<str:rut>', views.retirar_ficha_alumno, name='retirar_ficha_alumno'),
    path('pdf/habilidades_pragmaticas/', views.generate_doc_cotejo_hab_prag, name='generate_hab_prag'),
    path('pdf/habilidades_pragmaticas/<str:rut>', views.generate_doc_cotejo_hab_prag, name='generate_hab_prag'),
    path('pdf/habilidades_pragmaticas_confirmacion/download', views.generate_pdf_hab_prag, name='pdf_hab_prag'),
    path('pdf/anamnesis', views.generate_doc_anamnesis, name='generate_anamnesis'),
    path('pdf/anamnesis/<str:rut>', views.generate_doc_anamnesis, name='generate_anamnesis'),
    path('pdf/anamnesis_confirmacion/download', views.generate_pdf_anamnesis, name='pdf_anamnesis'),
    path('pdf/tecal', views.generate_doc_tecal, name='generate_tecal'),
    path('pdf/tecal/<str:rut>', views.generate_doc_tecal, name='generate_tecal'),
    path('pdf/tecal_confirmacion', views.confirmation_tecal, name="confirmation_tecal"),
    path('pdf/tecal_confirmacion/download', views.generate_pdf_tecal, name="pdf_tecal"),
    path('pdf/fonoaudiologica', views.generate_doc_fonoaudiologica, name='generate_fonoaudio'),
    path('pdf/fonoaudiologica/<str:rut>', views.generate_doc_fonoaudiologica, name='generate_fonoaudio'),
    path('pdf/fonoaudiologica_confirmacion/download', views.generate_pdf_fonoaudiologica, name="pdf_fonoaudio"),
    path('pdf/teprosif', views.generate_doc_teprosif, name='generate_teprosif'),
    path('pdf/teprosif/<str:rut>', views.generate_doc_teprosif, name='generate_teprosif'),
    path('pdf/teprosif_puntajes', views.generate_doc_final_teprosif, name='teprosif_puntajes'),
    path('pdf/teprosif_puntajes/download', views.generate_pdf_teprosif, name='pdf_teprosif'),
    path('pdf/stsg', views.generate_doc_stsg, name='generate_stsg'),
    path('pdf/stsg/<str:rut>', views.generate_doc_stsg, name='generate_stsg'),
    path('pdf/stsg_confirmacion/download', views.generate_pdf_stsg, name="pdf_stsg"),
]

palabritas_web/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('autenticacion.urls')),
    path('alumnos/', include('fichas_alumnos.urls')),
    path('cursos/', include('cursos.urls')),
    path('lista_espera/', include('lista_espera.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

fichas_alumnos/models.py
import os
from django.db import models
from django.core.validators import RegexValidator
from autenticacion.models import Usuario
from cursos.models import Curso

class FichaAlumno(models.Model):
    LISTAESPERA = 'lista_espera'
    DOCUMENTOSPENDIENTE = 'documentos_pendientes'
    CURSOASIGNADO = 'curso_asignado'
    RETIRADO = 'retirado'
    ESTADO = [
        (LISTAESPERA, ('En lista de espera')),
        (DOCUMENTOSPENDIENTE, ('Documentos pendientes')),
        (CURSOASIGNADO, ('Curso asignado')),
        (RETIRADO, ('Retirado')),
    ]

    REGEX_RUT_VALIDATOR = r"^(\d{1,3}(?:\d{3}){2}-[\dkK])$"

    rut = models.CharField(
            max_length=11,
            primary_key=True,
            validators=[RegexValidator(REGEX_RUT_VALIDATOR)],
            verbose_name="Rut alumno",
            help_text="El rut debe ser ingresado sin puntos y con guión."
            )
    nombre = models.CharField(max_length=255, null=False, blank=False)
    fecha_nacimiento = models.DateField()
    direccion = models.CharField(max_length=255, null=False, blank=False)
    nombre_padre = models.CharField(max_length=255, null=False, blank=False)
    nombre_madre = models.CharField(max_length=255, null=False, blank=False)
    telefono = models.CharField(max_length=255, null=False, blank=False)
    ficha_social = models.BooleanField(default=False)
    formulario_salud = models.BooleanField(default=False)
    anamnesis = models.BooleanField(default=False)
    certif_nacimiento = models.BooleanField(default=False)
    consent_fonoaudiologia = models.BooleanField(default=False)
    consent_vidasana = models.BooleanField(default=False)
    solicitud_textos = models.BooleanField(default=False)
    entrega_textos = models.BooleanField(default=False)
    colacion_celebracion = models.BooleanField(default=False)
    ficha_matricula = models.BooleanField(default=False)
    autorizacion_eval = models.BooleanField(default=False)
    formulario_reeval = models.BooleanField(default=False)
    formulario_fudei = models.BooleanField(default=False)
    informe_padres = models.BooleanField(default=False)
    eval_diagnostica = models.BooleanField(default=False)
    informe_semestral = models.BooleanField(default=False)
    peval_semestral = models.BooleanField(default=False)
    otros_docs_admin = models.CharField(max_length=255, null=True, blank=True)

    estado = models.CharField(
       max_length=32,
       choices=ESTADO,
       default=LISTAESPERA,
    )
    curso = models.ForeignKey(Curso, on_delete=models.DO_NOTHING, blank=True, null=True)

    class Meta:
        verbose_name = 'Ficha Alumno'
        verbose_name_plural = 'Fichas Alumnos'
        ordering = ['rut']
        permissions = (
            ('can_view_listado_fichas', 'Puede ver listado fichas alumnos'),
            ('can_view_ficha_completa', 'Puede ver ficha alumno completa'),
            ('can_retirar_ficha_alumno', 'Puede retirar ficha alumno'),
        )

    def __str__(self):
        return self.nombre

    def rut_formatted(self):

        rut = ""

        if len(self.rut) == 11:
            rut_1 = self.rut[:3]
            rut_2 = self.rut[3:6]
            rut_3 = self.rut[-5:]
            rut = (rut_1+"."+rut_2+"."+rut_3)
        if len(self.rut) == 10:
            rut_1 = self.rut[:2]
            rut_2 = self.rut[2:5]
            rut_3 = self.rut[-5:]
            rut = (rut_1+"."+rut_2+"."+rut_3)
        if len(self.rut) == 9:
            rut_1 = self.rut[:1]
            rut_2 = self.rut[1:4]
            rut_3 = self.rut[-5:]
            rut = (rut_1+"."+rut_2+"."+rut_3)

        return rut.upper()

    def asignar_curso(self, curso:Curso):
        if curso:
            self.curso = curso
            if self.estado == 'lista_espera':
                self.estado = 'curso_asignado'
            self.save()



def documento_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/alumno_<rut>/<filename>
    return 'banco_documento/alumno_{0}/{1}'.format(instance.alumno.rut, filename)

class BancoDocumento(models.Model):
    id = models.AutoField(primary_key=True)
    alumno = models.ForeignKey(FichaAlumno, on_delete=models.CASCADE)
    documento = models.FileField(max_length=500, upload_to=documento_directory_path)

    class Meta:
        verbose_name = 'Banco documento'
        verbose_name_plural = 'Banco documentos'
        ordering = ['id']
    def filename(self):
        return os.path.basename(self.documento.name)


def trabajo_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/alumno_<rut>/<filename>
    return 'trabajo/alumno_{0}/{1}'.format(instance.alumno.rut, filename)

class BancoTrabajo(models.Model):
    id = models.AutoField(primary_key=True)
    alumno = models.ForeignKey(FichaAlumno, on_delete=models.CASCADE)
    trabajo = models.FileField(max_length=500, upload_to=trabajo_directory_path)

    class Meta:
        verbose_name = 'Trabajo'
        verbose_name_plural = 'Trabajos'
        ordering = ['id']

    def filename(self):
        return os.path.basename(self.trabajo.name)


class AvanceAlumno(models.Model):
    id = models.AutoField(primary_key=True)
    alumno = models.ForeignKey(FichaAlumno, on_delete=models.CASCADE)
    comentario = models.CharField(max_length=1000, null=False, blank=False)
    editor = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    fecha_edicion = models.DateField(auto_now=True)
    modificado = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Avance'
        verbose_name_plural = 'Avances'
        ordering = ['id']

    def geteditor(self):
        return self.editor.nombre


class DetalleApoderado(models.Model):
    id = models.AutoField(primary_key=True)
    alumno = models.ForeignKey(FichaAlumno, on_delete=models.CASCADE)
    apoderado = models.ForeignKey(Usuario, on_delete=models.CASCADE, limit_choices_to={'groups__name': "Apoderado"})

    class Meta:
        verbose_name = 'Detalle Apoderado'
        verbose_name_plural = 'Detalle Apoderados'
        ordering = ['id']

    def getapoderado(self):
        return self.apoderado.nombre

fichas_alumnos/templates/listado_fichas_alumnos.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}Ficha alumnos{% endblock titulo %}

{% block content %}

<div class="col col-md-10 col-lg-8 mx-auto">

    {% if perms.fichas_alumnos.can_view_listado_fichas %}

        <div class="container">
            <h3 class="fw-bold mt-4 mb-3">Buscar alumno</h3>
            <form method="get" action="{% url 'listado_fichas_alumnos' %}" class="d-md-flex">

                <input name="nomrut" class="form-control mb-3 mb-md-0 me-md-3" type="search" placeholder="RUT o Nombre" aria-label="Search">
                <select name="curso" class="form-select mb-3 mb-md-0 me-md-3" aria-label="Default select example">
                    <option value="" selected hidden>Curso</option>
                    {% for c in curso %}
                        <option value="{{ c.nombre}}">{{ c.nombre }}</option>
                    {% endfor %}
                </select>
                <button class="btn btn-outline-success" type="submit">Buscar</button>
            </form>
        </div>

    {% endif %}

    
    <div class="d-flex justify-content-between mt-5 px-2">
        <h3 class="fw-bold">Alumnos</h3>
        {% if perms.fichas_alumnos.add_fichaalumno %}
            <a class="py-2" href="{% url 'agregar_ficha_alumno' %}">Agregar ficha</a> 
        {% endif %}
    </div>


    {% if listado %}
        <div class="table-responsive-md">
            <table class="table table-striped table-hover">
                <thead class="table-dark">
                    <tr>
                        <th scope="col">RUT</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Curso</th>
                    </tr>
                </thead>
                <tbody>
                    {% for alumno in listado %}

                        <tr role="button" onclick="window.location='{% url 'ficha_alumno' alumno.rut %}';">
                            <td class="align-middle">{{ alumno.rut_formatted }}</td>
                            <td class="align-middle">{{ alumno.nombre }}</td>
                            {% if alumno.curso %}
                                <td class="align-middle">{{ alumno.curso.nombre }}</td>
                            {% else %}
                                <td class="align-middle">No asignado</td>
                            {% endif %}
                        </tr>

                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}

        <h3 class="p-5">No hay alumnos que mostrar...</h3>

    {% endif %}

</div>

{% if request.session.pdf_tecal %}
    <script>
        window.onload = function(e){ 
            window.location='{% url 'pdf_tecal' %}';
        }
    </script>
{% elif request.session.pdf_hab_prag %}
    <script>
        window.onload = function(e){ 
            window.location='{% url 'pdf_hab_prag' %}';
        }
    </script>
{% elif request.session.pdf_stsg %}
    <script>
        window.onload = function(e){ 
            window.location='{% url 'pdf_stsg' %}';
        }
    </script>
{% elif request.session.pdf_fonoaudio %}
    <script>
        window.onload = function(e){ 
            window.location='{% url 'pdf_fonoaudio' %}';
        }
    </script>
{% elif request.session.pdf_teprosif %}
    <script>
        window.onload = function(e){ 
            window.location='{% url 'pdf_teprosif' %}';
        }
    </script>
{% elif request.session.pdf_anamnesis %}
    <script>
        window.onload = function(e){ 
            window.location='{% url 'pdf_anamnesis' %}';
        }
    </script>
{% endif %}

{% endblock content %}