cursos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.listado_cursos_view, name='listado_cursos'),
    path('agregar_curso/', views.agregar_curso_view, name='agregar_curso'),
    path('modificar_curso/<str:id>', views.modificar_curso_view, name='modificar_curso'),
    path('detalle_curso/<str:id>', views.detalle_curso_view, name='detalle_curso'),
    path('modificar_detalle_docente/<int:id>', views.modificar_detalle_docente_view, name='modificar_detalle_docente'),
    path('eliminar_detalle_docente/<int:id>', views.delete_detalle_docente_view, name='eliminar_detalle_docente'),
    path('modificar_cronograma_actividad/<int:id>', views.modificar_cronograma_actividad_view, name='modificar_cronograma_actividad'),
    path('eliminar_cronograma_actividad/<int:id>', views.delete_cronograma_actividad_view, name='eliminar_cronograma_actividad'),
    path('eliminar_trabajo/<int:id>', views.delete_banco_trabajo_view, name='eliminar_trabajo'),
]

palabritas_web/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('autenticacion.urls')),
    path('alumnos/', include('fichas_alumnos.urls')),
    path('cursos/', include('cursos.urls')),
    path('lista_espera/', include('lista_espera.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cursos/models.py
from django.db import models
import datetime
import os
from django.core.validators import RegexValidator
from autenticacion.models import Usuario
from PIL import Image
import filetype

class Nivel(models.Model):
    id = models.AutoField(primary_key=True)
    descripcion = models.CharField(max_length=100, unique=True, blank=False, null=False)

    class Meta:
        verbose_name = 'Nivel'
        verbose_name_plural = 'Niveles'
        ordering = ['id']

    def __str__(self):
        return self.descripcion


class Curso(models.Model):
    REGEX_LETRA = r"([a-zA-Z])"

    id = models.CharField(primary_key=True, max_length=20)
    nivel = models.ForeignKey(Nivel, on_delete=models.CASCADE)
    letra = models.CharField(
            max_length=1,
            blank=False, 
            null=False,
            validators=[RegexValidator(REGEX_LETRA)],
            )
    nombre = models.CharField(max_length=100, blank=False, null=False)
    periodo = models.CharField(max_length=4, default=datetime.datetime.now().year, blank=False, null=False)
    cupos = models.PositiveIntegerField(null=False)
    docente_jefe = models.ForeignKey(Usuario, on_delete=models.DO_NOTHING, blank=True, null=True, limit_choices_to={'groups__name': "Docente"})

    class Meta:
        verbose_name = 'Curso'
        verbose_name_plural = 'Cursos'
        ordering = ['id']
        permissions = (
            ('can_view_listado_cursos', 'Can view listado cursos'),
        )

    def __str__(self):
        return self.id


def actividad_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/alumno_<rut>/<filename>
    return 'cronograma_act/curso_{0}/{1}'.format(instance.curso.id, filename)

class CronogramaActividad(models.Model):
    id = models.AutoField(primary_key=True)
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)
    comentario = models.CharField(max_length=1000, null=False, blank=False)
    archivo = models.FileField(max_length=500, upload_to=actividad_directory_path, null=True, blank=True)
    editor = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    fecha_edicion = models.DateField(auto_now=True)
    modificado = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Cronograma actividad'
        verbose_name_plural = 'Cronograma de actividades'
        ordering = ['id']

    def geteditor(self):
        return self.editor.nombre

    def getcurso(self):
        return self.curso.nombre

    def filename(self):
        return os.path.basename(self.archivo.name)

    def is_image(self):
        return filetype.is_image(self.archivo.path)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.archivo and filetype.is_image(self.archivo.path):
            img = Image.open(self.archivo.path)
            if img.height > 720 or img.width > 1280:
                output_size = (1280, 720)
                img.thumbnail(output_size)
                img.save(self.archivo.path)


def trabajo_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/alumno_<rut>/<filename>
    return 'trabajo/curso_{0}/{1}'.format(instance.curso.id, filename)

class BancoTrabajo(models.Model):
    id = models.AutoField(primary_key=True)
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)
    trabajo = models.FileField(max_length=500, upload_to=trabajo_directory_path)

    class Meta:
        verbose_name = 'Trabajo curso'
        verbose_name_plural = 'Trabajos curso'
        ordering = ['id']

    def filename(self):
        return os.path.basename(self.trabajo.name)

    def getcurso(self):
        return self.curso.nombre


class DetalleDocente(models.Model):
    id = models.AutoField(primary_key=True)
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)
    docente = models.ForeignKey(Usuario, on_delete=models.CASCADE, limit_choices_to={'groups__name': "Docente"})
    asignatura = models.CharField(max_length=250, blank=False, null=False)

    class Meta:
        verbose_name = 'Detalle docente'
        verbose_name_plural = 'Detalle docentes'
        ordering = ['id']

    def getdocente(self):
        return self.docente.nombre

    def getcurso(self):
        return self.curso.nombre

cursos/forms.py
from django.forms import ModelForm, Textarea, FileInput
from .models import CronogramaActividad, Curso, DetalleDocente, BancoTrabajo

class FormAgregarCurso(ModelForm):

    class Meta:
        model = Curso
        fields = ['nivel', 'letra', 'cupos', 'docente_jefe',]


class FormModificarCurso(ModelForm):

    class Meta:
        model = Curso
        fields = ['cupos', 'docente_jefe',]

class FormCronActividades(ModelForm):

    class Meta:
        model = CronogramaActividad
        fields = ['comentario', 'archivo']
        widgets = {
            'comentario': Textarea(attrs={'rows': 3, 'class': "form-control"}),
            'archivo': FileInput(attrs={'class': "form-control"}),
        }

class FormDetalleDocente(ModelForm):

    class Meta:
        model = DetalleDocente
        fields = ['docente', 'asignatura']

class FormModificarDetalleDocente(ModelForm):

    class Meta:
        model = DetalleDocente
        fields = ['asignatura']

class FormTrabajoCurso(ModelForm):
    
    class Meta:
        model = BancoTrabajo
        fields = ['trabajo',]
        widgets = {
            'trabajo': FileInput(attrs={'class': "form-control"}),
        }

cursos/views.py
import datetime
from django.shortcuts import redirect, render
from django.db.models import Q
from django.contrib.auth.decorators import login_required, permission_required

from lista_espera.models import ListaEspera
from .models import CronogramaActividad, Curso, DetalleDocente, BancoTrabajo
from .forms import FormAgregarCurso, FormDetalleDocente, FormModificarCurso, FormCronActividades, FormModificarDetalleDocente, FormTrabajoCurso
from autenticacion.models import Usuario
from fichas_alumnos.models import FichaAlumno

@login_required
@permission_required('cursos.view_curso', raise_exception=True)
def listado_cursos_view(request):

    context = {}

    # Consigue una lista con los periodos de cada curso
    context['periodo'] = Curso.objects.order_by().values('periodo').distinct()

    # Consigue la lista de docentes
    docentes = Curso.objects.order_by().values('docente_jefe').distinct()
    context['docente'] = Usuario.objects.filter(id__in=docentes)

    # Revisa si el usuario es docente y si es que tiene cursos asginados
    if not request.user.has_perm('cursos.can_view_listado_cursos'):

        cursos = DetalleDocente.objects.filter(docente=request.user).order_by().values('curso_id').distinct()
        listado = Curso.objects.filter(Q(id__in=cursos) | Q(docente_jefe=request.user)).order_by('-periodo')
        context['listado'] = listado

    else:
        context['listado'] = Curso.objects.all().order_by('-periodo')

    # Métodos para filtrar búsqueda
    if request.method == 'GET':

        if request.GET.get('nombre') and request.GET.get('nombre') != "":
            query = request.GET.get('nombre')
            object_list =  context['listado'].filter(
                Q(nombre__icontains=query)
            )
            context['listado'] = object_list
        if request.user.has_perm('cursoscan_view_listado_cursos'):
            if request.GET.get('periodo') and request.GET.get('periodo') != "":
                query = request.GET.get('periodo')
                object_list =  context['listado'].filter(
                    Q(periodo=query)
                )
                context['listado'] = object_list
        if request.GET.get('docente') and request.GET.get('docente') != "":
            query = request.GET.get('docente')
            if query == 'No asignado':
                object_list =  context['listado'].filter(
                    Q(docente_jefe=None)
                )
            else:
                object_list =  context['listado'].filter(
                    Q(docente_jefe=query)
                )
            context['listado'] = object_list

    return render(request, 'listado_cursos.html', context)


@login_required
@permission_required('cursos.add_curso', raise_exception=True)
def agregar_curso_view(request):
    context = {}
    context['form'] = FormAgregarCurso

    if request.POST:
        form = FormAgregarCurso(request.POST)

        if form.is_valid():
            nivel = form.cleaned_data['nivel'].descripcion.capitalize()
            letra = form.cleaned_data['letra'].upper()
            periodo = datetime.datetime.now().year

            nuevo_curso = form.save(commit=False)
            nuevo_curso.id = "{0}{1}{2}".format(nivel[:(len(nivel)-7)], letra, periodo)
            nuevo_curso.nombre = "{0} {1}".format(nivel, letra)
            nuevo_curso.periodo = periodo
            if not Curso.objects.filter(id=nuevo_curso.id):
                nuevo_curso.save()
                return redirect('listado_cursos')
            
            form.add_error(None, "El curso que está intentando agregar ya existe.")

        context['form'] = form

    return render(request, 'formularios/curso_agregar_formulario.html', context)


@login_required
@permission_required('cursos.change_curso', raise_exception=True)
def modificar_curso_view(request, id):
    context = {}

    try:
        instance = Curso.objects.get(id=id)
    except:
        return redirect('listado_cursos')
    context['form'] = FormModificarCurso(instance=instance)
    context['id'] = id
    
    if request.POST:
        form = FormModificarCurso(request.POST, instance=instance)
        if form.is_valid():

            alumnos = FichaAlumno.objects.filter(curso=id).count()
            cupos = form.cleaned_data['cupos']
            curso_modificado = form.save(commit=False)
            if cupos >= alumnos:
                curso_modificado.save()
                return redirect('detalle_curso', id)
            else:
                form.add_error('cupos', "No pueden haber menos cupos que alumnos inscritos.")
                context['form'] = form

        else:
            context['form'] = form

    return render(request, 'formularios/curso_modificar_formulario.html', context)


@login_required
@permission_required('cursos.view_curso', raise_exception=True)
def detalle_curso_view(request, id):
    context = {}
    try:
        context['curso'] = Curso.objects.get(id=id)
    except:
        return redirect('listado_cursos')
    context['docente'] = DetalleDocente.objects.filter(curso_id=id)
    context['cron_actividad'] = CronogramaActividad.objects.filter(curso_id=id).order_by('-id')
    context['trabajos'] = BancoTrabajo.objects.filter(curso_id=id).order_by('-id')
    context['alumnos'] = FichaAlumno.objects.filter(curso_id=id).order_by('nombre')

    context['docente_form'] = FormDetalleDocente
    context['actividad_form'] = FormCronActividades
    context['trabajo_form'] = FormTrabajoCurso

    if 'error' in request.session:
        context['error'] = request.session['error']
        del request.session['error']
    if 'success' in request.session:
        context['success'] = request.session['success']
        del request.session['success']

    context['inscritos'] = FichaAlumno.objects.filter(curso_id=id).count()
    if context['curso'].cupos > context['inscritos']:
        context['cupos'] = context['curso'].cupos - context['inscritos']

        context['avanzan'] = ListaEspera.objects.filter(nivel=context['curso'].nivel).count()
        if context['avanzan'] > context['cupos']:
            context['avanzan'] = context['cupos']

    if request.method == 'POST':

        if request.POST.get('docente') and request.POST.get('asignatura'):
            # create a form instance and populate it with data from the request:
            form = FormDetalleDocente(request.POST)

            # check whether it's valid:
            if form.is_valid():
                nuevo_docente = form.save(commit=False)
                nuevo_docente.curso = Curso.objects.get(id=id)
                nuevo_docente.asignatura = nuevo_docente.asignatura.title()
                nuevo_docente.save()
            else:
                context['docente_form'] = form

        if request.POST.get('comentario'):
            # create a form instance and populate it with data from the request:
            form = FormCronActividades(request.POST, request.FILES)

            # check whether it's valid:
            if form.is_valid():
                nueva_actividad = form.save(commit=False)
                nueva_actividad.curso = Curso.objects.get(id=id)
                nueva_actividad.editor = request.user
                nueva_actividad.save()
            else:
                context['actividad_form'] = form

        if request.FILES.get('trabajo'):
            # create a form instance and populate it with data from the request:
            form = FormTrabajoCurso(request.POST, request.FILES)

            # check whether it's valid:
            if form.is_valid():
                nuevo_trabajo = form.save(commit=False)
                nuevo_trabajo.curso = Curso(id)
                nuevo_trabajo.save()

    return render(request, 'detalle_curso.html', context)


@login_required
@permission_required('cursos.change_detalledocente', raise_exception=True)
def modificar_detalle_docente_view(request, id):
    context = {}

    try:
        instance = DetalleDocente.objects.get(id=id)
    except:
        return redirect('listado_cursos')
    context['form'] = FormModificarDetalleDocente(instance=instance)
    context['instance'] = instance
    
    if request.POST:
        form = FormModificarDetalleDocente(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return redirect('detalle_curso', instance.curso.id)

        else:
            context['form'] = form

    return render(request, 'formularios/detalle_docente_modificar_formulario.html', context)


@login_required
@permission_required('cursos.delete_detalledocente', raise_exception=True)
def delete_detalle_docente_view(request, id):
    try:
        instance = DetalleDocente.objects.get(id=id)
    except:
        return redirect('listado_cursos')
    curso = instance.curso.id
    instance.delete()

    return redirect('detalle_curso', curso)


@login_required
@permission_required('cursos.change_cronogramaactividad', raise_exception=True)
def modificar_cronograma_actividad_view(request, id):
    context = {}

    try:
        instance = CronogramaActividad.objects.get(id=id)
    except:
        return redirect('listado_cursos')
    context['form'] = FormCronActividades(instance=instance)
    context['instance'] = instance
    

    if request.POST:
        print(request.POST)
        print(request.FILES)

        form = FormCronActividades(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            actividad_modificada = form.save(commit=False)
            actividad_modificada.modificado = True
            if request.POST.get('chkEliminarArchivo') == "on":
                actividad_modificada.archivo = None
            actividad_modificada.save()
            
            return redirect('detalle_curso', instance.curso.id)

        else:
            context['form'] = form

    return render(request, 'formularios/cronograma_actividad_modificar_formulario.html', context)


@login_required

cursos/templates/formularios/cronograma_actividad_modificar_formulario.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}Modificar actividad{% endblock titulo %}

{% block content %}

    <div class="container">
        <div class="col col-md-8 col-lg-6 mx-auto my-4">
            <p class="fs-5 fw-bold text-center">Modificar actividad</p>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <p>{{ form.comentario|as_crispy_field }}</p>
                {% if instance.archivo %}
                    {% if instance.is_image %}
                        <img class="img-fluid img-thumbnail mx-auto d-block" src="{% get_media_prefix %}{{ instance.archivo }}" alt="Imagen registro de actividad">
                    {% else %}
                        <a class="btn btn-outline-primary" href="{% get_media_prefix %}{{ instance.archivo }}" target="_blank">{{ instance.filename }}</a>
                    {% endif %}
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="chkEliminarArchivo" id="deleteArchivo">
                        <label class="form-check-label" for="deleteArchivo">
                            ¿Eliminar archivo?
                        </label>
                    </div>
                {% endif %}
                <p>{{ form.archivo|as_crispy_field }}</p>

                <a href="{% url 'detalle_curso' instance.curso.id %}" class="btn btn-secondary">Cancelar</a>
                <button class="btn btn-primary" type="submit">Modificar</button>
            </form>
        </div>
    </div>
    
{% endblock content %}

cursos/templates/formularios/curso_agregar_formulario.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}Agregar curso{% endblock titulo %}

{% block content %}

    <div class="container">
        <div class="col col-md-8 col-lg-6 mx-auto my-4">
            <p class="fs-5 fw-bold text-center">Agregar curso</p>
            <form method="post">
                {% csrf_token %}
                <p>{{ form.nivel|as_crispy_field }}</p>
                <p>{{ form.letra|as_crispy_field }}</p>
                <p>{{ form.cupos|as_crispy_field }}</p>
                <p>{{ form.docente_jefe|as_crispy_field }}</p>
                <button class="btn btn-primary" type="submit">Agregar</button>
            </form>
        </div>
    </div>
    
{% endblock content %}

cursos/templates/formularios/curso_modificar_formulario.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}Modificar curso{% endblock titulo %}

{% block content %}

    <div class="container">
        <div class="col col-md-8 col-lg-6 mx-auto my-4">
            <p class="fs-5 fw-bold text-center">Modificar curso</p>
            <form method="post">
                {% csrf_token %}
                <p>{{ form.cupos|as_crispy_field }}</p>
                <p>{{ form.docente_jefe|as_crispy_field }}</p>

                <a href="{% url 'detalle_curso' id %}" class="btn btn-secondary">Cancelar</a>
                <button class="btn btn-primary" type="submit">Modificar</button>
            </form>
        </div>
    </div>
    
{% endblock content %}

cursos/templates/formularios/detalle_docente_modificar_formulario.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}Modificar detalle docente{% endblock titulo %}

{% block content %}

    <div class="container">
        <div class="col col-md-8 col-lg-6 mx-auto my-4">
            <p class="fs-5 fw-bold text-center">Modificar detalle docente</p>
            <form method="post">
                {% csrf_token %}
                <p>
                    <label for="id_docente">Docente</label>
                    <input id="id_docente" class="form-control" type="text" value="{{ instance.docente }}" disabled readonly>
                </p>
                <p>{{ form|crispy }}</p>

                <a href="{% url 'detalle_curso' instance.curso.id %}" class="btn btn-secondary">Cancelar</a>
                <button class="btn btn-primary" type="submit">Modificar</button>
            </form>
        </div>
    </div>
    
{% endblock content %}